{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMUu9EW+oVM7xIPHiiw23Lz",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/jwork3838-cloud/MLB-hr-engine/blob/main/hr_dash_github.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# ============================================================================\n",
        "# MLB Home Run Predictor – Daily Prediction + GitHub Pages Dashboard\n",
        "# ============================================================================\n",
        "\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import requests\n",
        "import time\n",
        "import re\n",
        "import urllib.parse\n",
        "from datetime import datetime, timedelta\n",
        "from concurrent.futures import ThreadPoolExecutor, as_completed\n",
        "from sklearn.model_selection import train_test_split, GridSearchCV\n",
        "from sklearn.calibration import CalibratedClassifierCV\n",
        "from sklearn.metrics import roc_auc_score\n",
        "from xgboost import XGBClassifier\n",
        "import gspread\n",
        "from google.colab import auth, drive\n",
        "from google.auth import default\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "# ----------------------------------------------------------------------------\n",
        "# CONFIGURATION\n",
        "# ----------------------------------------------------------------------------\n",
        "TODAY = datetime.now().strftime('%Y-%m-%d')\n",
        "OPENWEATHER_API_KEY = \"3b1c666e88254b0827f0f37e326aa46f\"\n",
        "SHEET_ID = \"10ULW_blNg-yPEdruSUcoTe1fhyOwr_fNnoZGF7PWRw0\"\n",
        "ROLLING_DAYS = None\n",
        "\n",
        "# GitHub settings – REPLACE WITH YOUR INFO\n",
        "GITHUB_USERNAME = \"jwork3838-cloud\"\n",
        "GITHUB_REPO = \"MLB-hr-engine\"\n",
        "GITHUB_BRANCH = \"main\"\n",
        "\n",
        "# ----------------------------------------------------------------------------\n",
        "# HEADERS FOR SAVANT REQUESTS\n",
        "# ----------------------------------------------------------------------------\n",
        "SAVANT_HEADERS = {\n",
        "    \"User-Agent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36\",\n",
        "    \"Accept\": \"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\",\n",
        "}\n",
        "\n",
        "# ----------------------------------------------------------------------------\n",
        "# HARDCODED DATA (park factors, stadiums)\n",
        "# ----------------------------------------------------------------------------\n",
        "parkFactorHR = {\n",
        "    \"ARI\": 1.12, \"ATL\": 1.05, \"BAL\": 0.98, \"BOS\": 1.06, \"CHC\": 0.95,\n",
        "    \"CWS\": 0.92, \"CIN\": 1.23, \"CLE\": 0.88, \"COL\": 1.42, \"DET\": 1.00,\n",
        "    \"HOU\": 1.09, \"KC\": 1.02, \"LAA\": 1.01, \"LAD\": 1.08, \"MIA\": 0.91,\n",
        "    \"MIL\": 1.10, \"MIN\": 1.04, \"NYM\": 0.96, \"NYY\": 1.13, \"ATH\": 0.97,\n",
        "    \"PHI\": 1.07, \"PIT\": 0.94, \"SD\": 0.89, \"SF\": 0.85, \"SEA\": 0.93,\n",
        "    \"STL\": 0.99, \"TB\": 0.90, \"TEX\": 1.11, \"TOR\": 1.08, \"WSH\": 1.02\n",
        "}\n",
        "\n",
        "stadiumData = {\n",
        "    \"Diamondbacks\": {\"lat\": 33.445, \"lon\": -112.067, \"isDome\": True, \"abbrev\": \"ARI\", \"teamId\": 109},\n",
        "    \"Braves\":       {\"lat\": 33.891, \"lon\": -84.468,  \"isDome\": False, \"abbrev\": \"ATL\", \"teamId\": 144},\n",
        "    \"Orioles\":      {\"lat\": 39.284, \"lon\": -76.622,  \"isDome\": False, \"abbrev\": \"BAL\", \"teamId\": 110},\n",
        "    \"Red Sox\":      {\"lat\": 42.346, \"lon\": -71.097,  \"isDome\": False, \"abbrev\": \"BOS\", \"teamId\": 111},\n",
        "    \"Cubs\":         {\"lat\": 41.948, \"lon\": -87.656,  \"isDome\": False, \"abbrev\": \"CHC\", \"teamId\": 112},\n",
        "    \"White Sox\":    {\"lat\": 41.830, \"lon\": -87.634,  \"isDome\": False, \"abbrev\": \"CWS\", \"teamId\": 145},\n",
        "    \"Reds\":         {\"lat\": 39.097, \"lon\": -84.507,  \"isDome\": False, \"abbrev\": \"CIN\", \"teamId\": 113},\n",
        "    \"Guardians\":    {\"lat\": 41.496, \"lon\": -81.685,  \"isDome\": False, \"abbrev\": \"CLE\", \"teamId\": 114},\n",
        "    \"Rockies\":      {\"lat\": 39.756, \"lon\": -104.994, \"isDome\": False, \"abbrev\": \"COL\", \"teamId\": 115},\n",
        "    \"Tigers\":       {\"lat\": 42.339, \"lon\": -83.049,  \"isDome\": False, \"abbrev\": \"DET\", \"teamId\": 116},\n",
        "    \"Astros\":       {\"lat\": 29.757, \"lon\": -95.356,  \"isDome\": True,  \"abbrev\": \"HOU\", \"teamId\": 117},\n",
        "    \"Royals\":       {\"lat\": 39.051, \"lon\": -94.480,  \"isDome\": False, \"abbrev\": \"KC\",  \"teamId\": 118},\n",
        "    \"Angels\":       {\"lat\": 33.800, \"lon\": -117.883, \"isDome\": False, \"abbrev\": \"LAA\", \"teamId\": 108},\n",
        "    \"Dodgers\":      {\"lat\": 34.074, \"lon\": -118.240, \"isDome\": False, \"abbrev\": \"LAD\", \"teamId\": 119},\n",
        "    \"Marlins\":      {\"lat\": 25.778, \"lon\": -80.220,  \"isDome\": True,  \"abbrev\": \"MIA\", \"teamId\": 146},\n",
        "    \"Brewers\":      {\"lat\": 43.028, \"lon\": -87.971,  \"isDome\": True,  \"abbrev\": \"MIL\", \"teamId\": 158},\n",
        "    \"Twins\":        {\"lat\": 44.982, \"lon\": -93.278,  \"isDome\": False, \"abbrev\": \"MIN\", \"teamId\": 142},\n",
        "    \"Mets\":         {\"lat\": 40.757, \"lon\": -73.846,  \"isDome\": False, \"abbrev\": \"NYM\", \"teamId\": 121},\n",
        "    \"Yankees\":      {\"lat\": 40.829, \"lon\": -73.926,  \"isDome\": False, \"abbrev\": \"NYY\", \"teamId\": 147},\n",
        "    \"Athletics\":    {\"lat\": 38.580, \"lon\": -121.514, \"isDome\": False, \"abbrev\": \"ATH\", \"teamId\": 133},\n",
        "    \"Phillies\":     {\"lat\": 39.906, \"lon\": -75.167,  \"isDome\": False, \"abbrev\": \"PHI\", \"teamId\": 143},\n",
        "    \"Pirates\":      {\"lat\": 40.447, \"lon\": -80.006,  \"isDome\": False, \"abbrev\": \"PIT\", \"teamId\": 134},\n",
        "    \"Padres\":       {\"lat\": 32.707, \"lon\": -117.157, \"isDome\": False, \"abbrev\": \"SD\",  \"teamId\": 135},\n",
        "    \"Giants\":       {\"lat\": 37.779, \"lon\": -122.389, \"isDome\": False, \"abbrev\": \"SF\",  \"teamId\": 137},\n",
        "    \"Mariners\":     {\"lat\": 47.591, \"lon\": -122.333, \"isDome\": True,  \"abbrev\": \"SEA\", \"teamId\": 136},\n",
        "    \"Cardinals\":    {\"lat\": 38.623, \"lon\": -90.193,  \"isDome\": False, \"abbrev\": \"STL\", \"teamId\": 138},\n",
        "    \"Rays\":         {\"lat\": 27.768, \"lon\": -82.653,  \"isDome\": True,  \"abbrev\": \"TB\",  \"teamId\": 139},\n",
        "    \"Rangers\":      {\"lat\": 32.751, \"lon\": -97.083,  \"isDome\": True,  \"abbrev\": \"TEX\", \"teamId\": 140},\n",
        "    \"Blue Jays\":    {\"lat\": 43.641, \"lon\": -79.390,  \"isDome\": True,  \"abbrev\": \"TOR\", \"teamId\": 141},\n",
        "    \"Nationals\":    {\"lat\": 38.873, \"lon\": -77.007,  \"isDome\": False, \"abbrev\": \"WSH\", \"teamId\": 120},\n",
        "}\n",
        "\n",
        "# ----------------------------------------------------------------------------\n",
        "# HELPER FUNCTIONS\n",
        "# ----------------------------------------------------------------------------\n",
        "def fetch_json(url):\n",
        "    try:\n",
        "        r = requests.get(url, headers=SAVANT_HEADERS, timeout=15)\n",
        "        r.raise_for_status()\n",
        "        return r.json()\n",
        "    except Exception as e:\n",
        "        print(f\"❌ fetchJSON error: {e}\")\n",
        "        return None\n",
        "\n",
        "def fetch_csv(url):\n",
        "    try:\n",
        "        r = requests.get(url, headers=SAVANT_HEADERS, timeout=30)\n",
        "        r.raise_for_status()\n",
        "        return r.text\n",
        "    except Exception as e:\n",
        "        print(f\"❌ fetchCSV error: {e}\")\n",
        "        return None\n",
        "\n",
        "def get_pitcher_hand(pid):\n",
        "    data = fetch_json(f\"https://statsapi.mlb.com/api/v1/people/{pid}\")\n",
        "    if data and 'people' in data:\n",
        "        return data['people'][0].get('pitchHand', {}).get('code')\n",
        "    return None\n",
        "\n",
        "def get_batter_hand(bid):\n",
        "    data = fetch_json(f\"https://statsapi.mlb.com/api/v1/people/{bid}\")\n",
        "    if data and 'people' in data:\n",
        "        return data['people'][0].get('batSide', {}).get('code')\n",
        "    return None\n",
        "\n",
        "def calculate_woba_from_stat(stat):\n",
        "    try:\n",
        "        ab = stat.get('atBats', 0)\n",
        "        bb = stat.get('baseOnBalls', 0)\n",
        "        hbp = stat.get('hitByPitch', 0)\n",
        "        singles = stat.get('singles', 0)\n",
        "        doubles = stat.get('doubles', 0)\n",
        "        triples = stat.get('triples', 0)\n",
        "        hr = stat.get('homeRuns', 0)\n",
        "        woba = (0.69*bb + 0.69*hbp + 0.89*singles + 1.27*doubles + 1.62*triples + 2.10*hr) / (ab+bb+hbp) if (ab+bb+hbp) else 0\n",
        "        return woba\n",
        "    except:\n",
        "        return 0\n",
        "\n",
        "def calculate_iso_from_stat(stat):\n",
        "    try:\n",
        "        slg = stat.get('slugging', 0)\n",
        "        avg = stat.get('avg', 0)\n",
        "        return slg - avg if slg and avg else 0\n",
        "    except:\n",
        "        return 0\n",
        "\n",
        "def get_batter_platoon_splits(bid):\n",
        "    try:\n",
        "        url = f\"https://statsapi.mlb.com/api/v1/people/{bid}/stats?stats=statSplits&sitCodes=vl,vr&season=2026&group=hitting\"\n",
        "        data = fetch_json(url)\n",
        "        if not data or 'stats' not in data:\n",
        "            return {}\n",
        "        splits = data['stats'][0].get('splits', [])\n",
        "        result = {}\n",
        "        for split in splits:\n",
        "            code = split.get('split', {}).get('code')\n",
        "            stat = split.get('stat', {})\n",
        "            if code == 'vl':\n",
        "                result['wOBA_vs_L'] = calculate_woba_from_stat(stat)\n",
        "                result['ISO_vs_L'] = calculate_iso_from_stat(stat)\n",
        "            elif code == 'vr':\n",
        "                result['wOBA_vs_R'] = calculate_woba_from_stat(stat)\n",
        "                result['ISO_vs_R'] = calculate_iso_from_stat(stat)\n",
        "        return result\n",
        "    except Exception:\n",
        "        return {}\n",
        "\n",
        "def get_roster_batters(tid):\n",
        "    data = fetch_json(f\"https://statsapi.mlb.com/api/v1/teams/{tid}/roster?season=2026\")\n",
        "    if not data or 'roster' not in data:\n",
        "        return []\n",
        "    return [p['person']['id'] for p in data['roster'] if p['position']['type'] != 'Pitcher']\n",
        "\n",
        "def get_hot_streak(bid, target_date, days=7):\n",
        "    try:\n",
        "        start = (datetime.strptime(target_date, '%Y-%m-%d') - timedelta(days=days)).strftime('%Y-%m-%d')\n",
        "        url = f\"https://statsapi.mlb.com/api/v1/people/{bid}/stats?stats=gameLog&group=hitting&startDate={start}&endDate={target_date}\"\n",
        "        data = fetch_json(url)\n",
        "        if not data or not data.get('stats') or not data['stats'][0].get('splits'):\n",
        "            return None\n",
        "        totals = {'pa':0, 'ab':0, 'singles':0, 'doubles':0, 'triples':0, 'hr':0, 'bb':0, 'hbp':0}\n",
        "        for split in data['stats'][0]['splits']:\n",
        "            s = split['stat']\n",
        "            totals['pa'] += s.get('plateAppearances',0)\n",
        "            totals['ab'] += s.get('atBats',0)\n",
        "            totals['hr'] += s.get('homeRuns',0)\n",
        "            totals['bb'] += s.get('baseOnBalls',0)\n",
        "            totals['hbp'] += s.get('hitByPitch',0)\n",
        "            hits = s.get('hits',0)\n",
        "            doubles = s.get('doubles',0)\n",
        "            triples = s.get('triples',0)\n",
        "            totals['singles'] += hits - doubles - triples - totals['hr']\n",
        "            totals['doubles'] += doubles\n",
        "            totals['triples'] += triples\n",
        "        if totals['pa'] == 0:\n",
        "            return None\n",
        "        iso = (totals['doubles'] + totals['triples']*2 + totals['hr']*3) / max(1, totals['ab'])\n",
        "        woba = (0.69*(totals['bb']+totals['hbp']) + 0.89*totals['singles'] + 1.27*totals['doubles'] + 1.62*totals['triples'] + 2.10*totals['hr']) / totals['pa']\n",
        "        hr_rate = totals['hr'] / totals['pa']\n",
        "        return {'hot_pa': totals['pa'], 'hot_iso': iso, 'hot_woba': woba, 'hot_hr_rate': hr_rate}\n",
        "    except Exception:\n",
        "        return None\n",
        "\n",
        "def parse_csv(csv_text):\n",
        "    return pd.read_csv(pd.io.common.StringIO(csv_text)).to_dict(orient='records')\n",
        "\n",
        "def safe_get(obj, key, default=0):\n",
        "    if obj is None: return default\n",
        "    return obj.get(key, default)\n",
        "\n",
        "# ----------------------------------------------------------------------------\n",
        "# FETCH PLATE DISCIPLINE\n",
        "# ----------------------------------------------------------------------------\n",
        "def fetch_plate_discipline():\n",
        "    url = \"https://baseballsavant.mlb.com/leaderboard/custom?year=2026&type=batter&selections=player_id,last_name,first_name,z_swing_percent,oz_swing_percent,whiff_percent&min_pa=50&csv=true\"\n",
        "    headers = {\"User-Agent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36\"}\n",
        "    try:\n",
        "        r = requests.get(url, headers=headers, timeout=30)\n",
        "        r.raise_for_status()\n",
        "        df = pd.read_csv(pd.io.common.StringIO(r.text))\n",
        "        df = df.rename(columns={\n",
        "            \"z_swing_percent\": \"z_swing_pct\",\n",
        "            \"oz_swing_percent\": \"o_swing_pct\",\n",
        "            \"whiff_percent\": \"whiff_pct\"\n",
        "        })\n",
        "        df[\"contact_pct\"] = 100 - df[\"whiff_pct\"]\n",
        "        plate_dict = {}\n",
        "        for _, row in df.iterrows():\n",
        "            pid = int(row[\"player_id\"])\n",
        "            plate_dict[pid] = {\n",
        "                \"o_swing_pct\": row[\"o_swing_pct\"],\n",
        "                \"z_swing_pct\": row[\"z_swing_pct\"],\n",
        "                \"contact_pct\": row[\"contact_pct\"]\n",
        "            }\n",
        "        print(f\"✅ Fetched plate discipline for {len(plate_dict)} batters.\")\n",
        "        return plate_dict\n",
        "    except Exception as e:\n",
        "        print(f\"⚠️ Could not fetch plate discipline: {e}\")\n",
        "        return {}\n",
        "\n",
        "# ----------------------------------------------------------------------------\n",
        "# LOAD STATIC STATCAST DATA\n",
        "# ----------------------------------------------------------------------------\n",
        "def load_static_csvs():\n",
        "    print(\"Loading static Statcast CSVs...\")\n",
        "    batter_csv = fetch_csv(\"https://baseballsavant.mlb.com/statcast_leaderboard?type=batter&year=2026&position=&team=&min=q&csv=true\")\n",
        "    pitcher_csv = fetch_csv(\"https://baseballsavant.mlb.com/statcast_leaderboard?type=pitcher&year=2026&position=&team=&min=q&csv=true\")\n",
        "    expected_csv = fetch_csv(\"https://baseballsavant.mlb.com/leaderboard/expected_statistics?type=batter&year=2026&position=&team=&min=q&csv=true\")\n",
        "    batspeed_csv = fetch_csv(\"https://baseballsavant.mlb.com/leaderboard/bat-tracking?year=2026&csv=true\")\n",
        "    pitcher_exp_csv = fetch_csv(\"https://baseballsavant.mlb.com/leaderboard/expected_statistics?type=pitcher&year=2026&position=&team=&min=q&csv=true\")\n",
        "    pitch_movement_csv = fetch_csv(\"https://baseballsavant.mlb.com/leaderboard/pitch-movement?year=2026&csv=true\")\n",
        "    if not batter_csv or not pitcher_csv:\n",
        "        raise ValueError(\"Failed to download core CSVs.\")\n",
        "    all_batters = {int(r['player_id']): r for r in parse_csv(batter_csv)}\n",
        "    all_pitchers = {int(r['player_id']): r for r in parse_csv(pitcher_csv)}\n",
        "    expected = {int(r['player_id']): r for r in parse_csv(expected_csv)}\n",
        "    batspeed = {int(r['id']): r for r in parse_csv(batspeed_csv) if r.get('id')}\n",
        "    pitcher_exp = {int(r['player_id']): r for r in parse_csv(pitcher_exp_csv)}\n",
        "    # Pitch movement: aggregate per pitcher (fastball only)\n",
        "    pitch_movement = parse_csv(pitch_movement_csv) if pitch_movement_csv else []\n",
        "    pitcher_arsenal = {}\n",
        "    for row in pitch_movement:\n",
        "        pid = int(row['pitcher_id'])\n",
        "        pitch_type = row.get('pitch_type', '').upper()\n",
        "        if pitch_type in ('FF', '4-Seam Fastball'):\n",
        "            pitcher_arsenal[pid] = {\n",
        "                'fb_velo': row.get('avg_speed', 0),\n",
        "                'spin_rate': row.get('spin_rate', 0),\n",
        "                'horiz_break': row.get('horizontal_break', 0),\n",
        "                'vert_break': row.get('vertical_break', 0)\n",
        "            }\n",
        "    print(f\"Loaded: batters={len(all_batters)}, pitchers={len(all_pitchers)}, expected={len(expected)}, batspeed={len(batspeed)}, pitcher_exp={len(pitcher_exp)}, arsenal={len(pitcher_arsenal)}\")\n",
        "    return all_batters, all_pitchers, expected, batspeed, pitcher_exp, pitcher_arsenal\n",
        "\n",
        "# ----------------------------------------------------------------------------\n",
        "# FETCH TODAY'S FEATURES\n",
        "# ----------------------------------------------------------------------------\n",
        "def fetch_todays_features(plate_dict, static_data):\n",
        "    (all_batters, all_pitchers, expected, batspeed, pitcher_exp, pitcher_arsenal) = static_data\n",
        "    print(f\"\\n📡 Fetching today's schedule ({TODAY}) and building features...\")\n",
        "    schedule = fetch_json(f\"https://statsapi.mlb.com/api/v1/schedule?sportId=1&date={TODAY}&hydrate=probablePitcher\")\n",
        "    if not schedule or not schedule.get('dates'):\n",
        "        raise ValueError(\"No games found for today.\")\n",
        "    games = schedule['dates'][0].get('games', [])\n",
        "    print(f\"Found {len(games)} games.\")\n",
        "\n",
        "    starters = []\n",
        "    team_ids = set()\n",
        "    game_times = {}\n",
        "    for g in games:\n",
        "        away = g['teams']['away']['team']\n",
        "        home = g['teams']['home']['team']\n",
        "        team_ids.add(away['id']); team_ids.add(home['id'])\n",
        "        game_time = g.get('gameDate')\n",
        "        if game_time:\n",
        "            hour = int(game_time[11:13])\n",
        "            is_day = hour < 18\n",
        "            game_times[g['gamePk']] = {'is_day': is_day}\n",
        "        for side in ('away','home'):\n",
        "            p = g['teams'][side].get('probablePitcher')\n",
        "            if p:\n",
        "                pitcher_name = p.get('fullName', 'Unknown')\n",
        "                starters.append({\n",
        "                    'id': p['id'],\n",
        "                    'name': pitcher_name,\n",
        "                    'teamId': g['teams'][side]['team']['id'],\n",
        "                    'hand': None,\n",
        "                    'gamePk': g['gamePk']\n",
        "                })\n",
        "    print(f\"Probable starters: {len(starters)}\")\n",
        "\n",
        "    # Pitcher hands\n",
        "    with ThreadPoolExecutor(max_workers=10) as ex:\n",
        "        fut = {ex.submit(get_pitcher_hand, s['id']): s for s in starters}\n",
        "        for f in as_completed(fut):\n",
        "            s = fut[f]\n",
        "            s['hand'] = f.result()\n",
        "            print(f\"{s['name']}: {s['hand'] or 'unknown'}\")\n",
        "\n",
        "    # Rosters\n",
        "    print(\"\\nFetching active rosters...\")\n",
        "    roster_batters = {}\n",
        "    with ThreadPoolExecutor(max_workers=10) as ex:\n",
        "        fut = {ex.submit(get_roster_batters, tid): tid for tid in team_ids}\n",
        "        for f in as_completed(fut):\n",
        "            tid = fut[f]\n",
        "            batters = f.result()\n",
        "            if batters:\n",
        "                roster_batters[tid] = set(batters)\n",
        "                print(f\"Team {tid}: {len(batters)} batters\")\n",
        "            else:\n",
        "                print(f\"⚠️ No batters for team {tid}\")\n",
        "\n",
        "    # Batter hands, platoon splits & hot streaks\n",
        "    all_batter_ids = set()\n",
        "    for s in roster_batters.values():\n",
        "        all_batter_ids.update(s)\n",
        "    print(f\"\\nFetching batter handedness, platoon splits, hot streaks for {len(all_batter_ids)} batters...\")\n",
        "    batter_hand = {}\n",
        "    batter_platoon = {}\n",
        "    hot_streak = {}\n",
        "    with ThreadPoolExecutor(max_workers=10) as ex:\n",
        "        hand_fut = {ex.submit(get_batter_hand, bid): bid for bid in all_batter_ids}\n",
        "        split_fut = {ex.submit(get_batter_platoon_splits, bid): bid for bid in all_batter_ids}\n",
        "        streak_fut = {ex.submit(get_hot_streak, bid, TODAY): bid for bid in all_batter_ids}\n",
        "        for f in as_completed(hand_fut):\n",
        "            bid = hand_fut[f]\n",
        "            try:\n",
        "                batter_hand[bid] = f.result()\n",
        "            except:\n",
        "                batter_hand[bid] = None\n",
        "        for f in as_completed(split_fut):\n",
        "            bid = split_fut[f]\n",
        "            try:\n",
        "                batter_platoon[bid] = f.result()\n",
        "            except:\n",
        "                batter_platoon[bid] = {}\n",
        "        for f in as_completed(streak_fut):\n",
        "            bid = streak_fut[f]\n",
        "            try:\n",
        "                hot_streak[bid] = f.result()\n",
        "            except:\n",
        "                hot_streak[bid] = None\n",
        "    print(f\"Batter hands: {len(batter_hand)}, platoon splits: {len(batter_platoon)}, hot streaks: {len(hot_streak)}\")\n",
        "\n",
        "    print(\"\\nBuilding feature rows...\")\n",
        "    features = []\n",
        "    for g in games:\n",
        "        away_id = g['teams']['away']['team']['id']\n",
        "        home_id = g['teams']['home']['team']['id']\n",
        "        away_name = g['teams']['away']['team']['name']\n",
        "        home_name = g['teams']['home']['team']['name']\n",
        "        game_pk = g['gamePk']\n",
        "        is_day = game_times.get(game_pk, {}).get('is_day', False)\n",
        "\n",
        "        away_starter = next((s for s in starters if s['teamId'] == away_id), None)\n",
        "        home_starter = next((s for s in starters if s['teamId'] == home_id), None)\n",
        "        away_batters = roster_batters.get(away_id, set())\n",
        "        home_batters = roster_batters.get(home_id, set())\n",
        "        if not away_starter or not home_starter or not away_batters or not home_batters:\n",
        "            print(f\"Skipping {away_name} @ {home_name} – missing data\")\n",
        "            continue\n",
        "\n",
        "        # Weather\n",
        "        stadium_key = next((k for k,v in stadiumData.items() if v['teamId'] == home_id), None)\n",
        "        stadium = stadiumData.get(stadium_key)\n",
        "        weather = {'temp':70, 'windSpeed':0, 'windDeg':0}\n",
        "        if stadium and not stadium['isDome']:\n",
        "            wx_url = f\"https://api.openweathermap.org/data/2.5/weather?lat={stadium['lat']}&lon={stadium['lon']}&appid={OPENWEATHER_API_KEY}&units=imperial\"\n",
        "            wx_data = fetch_json(wx_url)\n",
        "            if wx_data and 'main' in wx_data:\n",
        "                weather = {\n",
        "                    'temp': wx_data['main']['temp'],\n",
        "                    'windSpeed': wx_data.get('wind',{}).get('speed',0),\n",
        "                    'windDeg': wx_data.get('wind',{}).get('deg',0),\n",
        "                }\n",
        "                print(f\"   Weather for {home_name}: {weather['temp']}°F, wind {weather['windSpeed']} mph\")\n",
        "            else:\n",
        "                print(f\"   ⚠️ Weather failed for {home_name}\")\n",
        "        elif stadium and stadium['isDome']:\n",
        "            print(f\"   {home_name} is a dome – weather not needed\")\n",
        "        home_abbrev = stadium['abbrev'] if stadium else home_name[:3].upper()\n",
        "        park_factor = parkFactorHR.get(home_abbrev, 1.0)\n",
        "\n",
        "        def build_row(bid, starter):\n",
        "            b = all_batters.get(bid)\n",
        "            if not b: return None\n",
        "            hand = batter_hand.get(bid, '')\n",
        "            platoon = 1 if hand == 'S' or (hand == 'L' and starter['hand'] == 'R') or (hand == 'R' and starter['hand'] == 'L') else 0\n",
        "            # Plate discipline\n",
        "            disc = plate_dict.get(bid, {})\n",
        "            o_swing = disc.get(\"o_swing_pct\", 0)\n",
        "            z_swing = disc.get(\"z_swing_pct\", 0)\n",
        "            contact = disc.get(\"contact_pct\", 0)\n",
        "            # Platoon splits\n",
        "            splits = batter_platoon.get(bid, {})\n",
        "            wOBA_vs_L = splits.get('wOBA_vs_L', 0)\n",
        "            wOBA_vs_R = splits.get('wOBA_vs_R', 0)\n",
        "            ISO_vs_L = splits.get('ISO_vs_L', 0)\n",
        "            ISO_vs_R = splits.get('ISO_vs_R', 0)\n",
        "            # Batted ball / expected\n",
        "            hard_hit = expected.get(bid, {}).get('ev95percent', 0)\n",
        "            gb = b.get('gb', 0)\n",
        "            fb_ld = b.get('fbld', 0)\n",
        "            # Pitcher stats\n",
        "            pitcher_stats = all_pitchers.get(starter['id'], {})\n",
        "            pitcher_exp_stats = pitcher_exp.get(starter['id'], {})\n",
        "            pitcher_xwoba = pitcher_exp_stats.get('xwoba', 0)\n",
        "            pitcher_xslg = pitcher_exp_stats.get('xslg', 0)\n",
        "            pitcher_xba = pitcher_exp_stats.get('xba', 0)\n",
        "            pitcher_hr_fb = pitcher_exp_stats.get('hr_fb_rate', 0) or pitcher_stats.get('hr_fb_rate', 0)\n",
        "            arm = pitcher_arsenal.get(starter['id'], {})\n",
        "            fb_velo = arm.get('fb_velo', 0)\n",
        "            spin_rate = arm.get('spin_rate', 0)\n",
        "            horiz_break = arm.get('horiz_break', 0)\n",
        "            vert_break = arm.get('vert_break', 0)\n",
        "\n",
        "            row = {\n",
        "                'batter_name': b['last_name, first_name'],\n",
        "                'batter_id': bid,\n",
        "                'batter_hand': hand,\n",
        "                'pitcher_name': starter['name'],\n",
        "                'pitcher_id': starter['id'],\n",
        "                'pitcher_hand': starter['hand'],\n",
        "                'home_team': home_abbrev,\n",
        "                'park_factor_hr': park_factor,\n",
        "                'temperature': weather['temp'],\n",
        "                'wind_speed': weather['windSpeed'],\n",
        "                'wind_direction': weather['windDeg'],\n",
        "                'is_day_game': 1 if is_day else 0,\n",
        "                'platoon_advantage': platoon,\n",
        "                'avg_hit_speed': b.get('avg_hit_speed', 0),\n",
        "                'barrel_rate': b.get('brl_percent', 0),\n",
        "                'hot_woba': safe_get(hot_streak.get(bid), 'hot_woba'),\n",
        "                'hot_iso': safe_get(hot_streak.get(bid), 'hot_iso'),\n",
        "                'avg_bat_speed': safe_get(batspeed.get(bid), 'avg_bat_speed'),\n",
        "                'hard_hit_rate': hard_hit,\n",
        "                'gb_pct': gb,\n",
        "                'fb_ld_pct': fb_ld,\n",
        "                'o_swing_pct': o_swing,\n",
        "                'z_swing_pct': z_swing,\n",
        "                'contact_pct': contact,\n",
        "                'wOBA_vs_L': wOBA_vs_L,\n",
        "                'wOBA_vs_R': wOBA_vs_R,\n",
        "                'ISO_vs_L': ISO_vs_L,\n",
        "                'ISO_vs_R': ISO_vs_R,\n",
        "                'pitcher_xwoba': pitcher_xwoba,\n",
        "                'pitcher_xslg': pitcher_xslg,\n",
        "                'pitcher_xba': pitcher_xba,\n",
        "                'pitcher_hr_fb_rate': pitcher_hr_fb,\n",
        "                'pitcher_fb_velo': fb_velo,\n",
        "                'pitcher_spin_rate': spin_rate,\n",
        "                'pitcher_horiz_break': horiz_break,\n",
        "                'pitcher_vert_break': vert_break,\n",
        "                'actual_hr': 0  # no labels for prediction\n",
        "            }\n",
        "            return row\n",
        "\n",
        "        for bid in away_batters:\n",
        "            row = build_row(bid, home_starter)\n",
        "            if row: features.append(row)\n",
        "        for bid in home_batters:\n",
        "            row = build_row(bid, away_starter)\n",
        "            if row: features.append(row)\n",
        "\n",
        "    if not features:\n",
        "        raise ValueError(\"No features generated for today.\")\n",
        "    df = pd.DataFrame(features)\n",
        "    print(f\"✅ Built {len(df)} feature rows for {TODAY}.\")\n",
        "    return df\n",
        "\n",
        "# ----------------------------------------------------------------------------\n",
        "# LOAD TRAINING DATA FROM GOOGLE SHEET\n",
        "# ----------------------------------------------------------------------------\n",
        "def load_training_data():\n",
        "    print(\"\\n📚 Loading training data from Google Sheet...\")\n",
        "    auth.authenticate_user()\n",
        "    creds, _ = default()\n",
        "    gc = gspread.authorize(creds)\n",
        "    sh = gc.open_by_key(SHEET_ID)\n",
        "    worksheet = sh.sheet1\n",
        "    data = worksheet.get_all_values()\n",
        "    if len(data) < 2:\n",
        "        raise ValueError(\"Sheet has no training data. Run backfill first.\")\n",
        "    df = pd.DataFrame(data[1:], columns=data[0])\n",
        "    df['hr_training_date'] = pd.to_datetime(df['hr_training_date'])\n",
        "    if ROLLING_DAYS:\n",
        "        cutoff = datetime.now() - timedelta(days=ROLLING_DAYS)\n",
        "        df = df[df['hr_training_date'] >= cutoff]\n",
        "    # Convert numeric columns\n",
        "    numeric_cols = [\n",
        "        'actual_hr', 'avg_hit_speed', 'barrel_rate', 'hot_woba', 'hot_iso',\n",
        "        'platoon_advantage', 'park_factor_hr', 'temperature', 'wind_speed',\n",
        "        'avg_bat_speed', 'pitcher_avg_hit_speed', 'hard_hit_rate', 'gb_pct',\n",
        "        'fb_ld_pct', 'o_swing_pct', 'z_swing_pct', 'contact_pct',\n",
        "        'wOBA_vs_L', 'wOBA_vs_R', 'ISO_vs_L', 'ISO_vs_R', 'pitcher_xwoba',\n",
        "        'pitcher_xslg', 'pitcher_xba', 'pitcher_hr_fb_rate', 'pitcher_fb_velo',\n",
        "        'pitcher_spin_rate', 'pitcher_horiz_break', 'pitcher_vert_break', 'is_day_game'\n",
        "    ]\n",
        "    for col in numeric_cols:\n",
        "        if col in df.columns:\n",
        "            df[col] = pd.to_numeric(df[col], errors='coerce')\n",
        "    df.fillna(0, inplace=True)\n",
        "    print(f\"Training rows: {len(df)} | Positive: {df['actual_hr'].sum()} | Negative: {len(df)-df['actual_hr'].sum()}\")\n",
        "    return df\n",
        "\n",
        "# ----------------------------------------------------------------------------\n",
        "# TRAIN MODEL AND PREDICT\n",
        "# ----------------------------------------------------------------------------\n",
        "def train_and_predict(df_train, df_pred):\n",
        "    feature_cols = [\n",
        "        'avg_hit_speed', 'barrel_rate', 'hot_woba', 'hot_iso',\n",
        "        'platoon_advantage', 'park_factor_hr', 'temperature', 'wind_speed',\n",
        "        'is_day_game', 'avg_bat_speed', 'hard_hit_rate', 'gb_pct', 'fb_ld_pct',\n",
        "        'o_swing_pct', 'z_swing_pct', 'contact_pct',\n",
        "        'wOBA_vs_L', 'wOBA_vs_R', 'ISO_vs_L', 'ISO_vs_R',\n",
        "        'pitcher_xwoba', 'pitcher_xslg', 'pitcher_xba', 'pitcher_hr_fb_rate',\n",
        "        'pitcher_fb_velo', 'pitcher_spin_rate', 'pitcher_horiz_break', 'pitcher_vert_break'\n",
        "    ]\n",
        "    for col in feature_cols:\n",
        "        if col not in df_train.columns:\n",
        "            df_train[col] = 0\n",
        "        if col not in df_pred.columns:\n",
        "            df_pred[col] = 0\n",
        "    X = df_train[feature_cols]\n",
        "    y = df_train['actual_hr']\n",
        "\n",
        "    X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)\n",
        "    scale_pos_weight = (len(y_tr) - y_tr.sum()) / y_tr.sum() if y_tr.sum() > 0 else 1\n",
        "\n",
        "    xgb = XGBClassifier(random_state=42, scale_pos_weight=scale_pos_weight, eval_metric='logloss', use_label_encoder=False)\n",
        "    param_grid = {'n_estimators': [100, 200], 'max_depth': [4, 6], 'learning_rate': [0.05, 0.1], 'subsample': [0.8, 1.0]}\n",
        "    grid = GridSearchCV(xgb, param_grid, cv=3, scoring='roc_auc', n_jobs=-1, verbose=0)\n",
        "    grid.fit(X_tr, y_tr)\n",
        "    best_raw = grid.best_estimator_\n",
        "    print(f\"Best params: {grid.best_params_}, CV AUC: {grid.best_score_:.4f}\")\n",
        "\n",
        "    calibrated = CalibratedClassifierCV(best_raw, method='sigmoid', cv=3)\n",
        "    calibrated.fit(X_tr, y_tr)\n",
        "    y_cal = calibrated.predict_proba(X_te)[:, 1]\n",
        "    auc = roc_auc_score(y_te, y_cal)\n",
        "    print(f\"Test AUC: {auc:.4f}\")\n",
        "\n",
        "    imp = pd.Series(best_raw.feature_importances_, index=feature_cols).sort_values(ascending=False)\n",
        "    print(\"\\nTop 10 features:\\n\", imp.tail(10))\n",
        "\n",
        "    X_pred = df_pred[feature_cols]\n",
        "    probs = calibrated.predict_proba(X_pred)[:, 1]\n",
        "    df_pred['hr_probability'] = probs\n",
        "    return df_pred\n",
        "\n",
        "# ----------------------------------------------------------------------------\n",
        "# DRAFTKINGS ODDS FETCH\n",
        "# ----------------------------------------------------------------------------\n",
        "def fetch_dk_hr_data():\n",
        "    DK_LEAGUE_ID = \"84240\"\n",
        "    DK_HR_SUBCATEGORY_ID = \"17319\"\n",
        "    DK_SITE = \"US-PA-SB\"\n",
        "\n",
        "    ev_filter = (\n",
        "        f\"$filter=leagueId eq '{DK_LEAGUE_ID}' AND \"\n",
        "        f\"clientMetadata/Subcategories/any(s: s/Id eq '{DK_HR_SUBCATEGORY_ID}')\"\n",
        "    )\n",
        "    mk_filter = (\n",
        "        f\"$filter=clientMetadata/subCategoryId eq '{DK_HR_SUBCATEGORY_ID}' AND \"\n",
        "        f\"tags/all(t: t ne 'SportcastBetBuilder')\"\n",
        "    )\n",
        "    tv_query = f\"{DK_LEAGUE_ID},{DK_HR_SUBCATEGORY_ID}\"\n",
        "\n",
        "    ev_q = urllib.parse.quote(ev_filter, safe='')\n",
        "    mk_q = urllib.parse.quote(mk_filter, safe='')\n",
        "    tv_q = urllib.parse.quote(tv_query, safe='')\n",
        "\n",
        "    url = (\n",
        "        f\"https://sportsbook-nash.draftkings.com/sites/{DK_SITE}\"\n",
        "        f\"/api/sportscontent/controldata/league/leagueSubcategory/v1/markets\"\n",
        "        f\"?isBatchable=false&templateVars={tv_q}\"\n",
        "        f\"&eventsQuery={ev_q}\"\n",
        "        f\"&marketsQuery={mk_q}\"\n",
        "        f\"&include=Events&entity=events\"\n",
        "    )\n",
        "\n",
        "    headers = {\n",
        "        \"Accept\": \"application/json, text/plain, */*\",\n",
        "        \"Accept-Language\": \"en-US,en;q=0.9\",\n",
        "        \"Origin\": \"https://sportsbook.draftkings.com\",\n",
        "        \"Referer\": (\n",
        "            \"https://sportsbook.draftkings.com/leagues/baseball/mlb\"\n",
        "            \"?category=games&subcategory=batter-props&nav_1=home-runs\"\n",
        "        ),\n",
        "        \"User-Agent\": (\n",
        "            \"Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) \"\n",
        "            \"AppleWebKit/605.1.15 (KHTML, like Gecko) \"\n",
        "            \"Version/18.0 Mobile/15E148 Safari/604.1\"\n",
        "        ),\n",
        "    }\n",
        "    r = requests.get(url, headers=headers, timeout=30)\n",
        "    if r.status_code != 200:\n",
        "        raise RuntimeError(f\"DraftKings HTTP {r.status_code}: {r.text[:200]}\")\n",
        "    return r.json()\n",
        "\n",
        "def fetch_draftkings_odds():\n",
        "    data = fetch_dk_hr_data()\n",
        "    events     = data.get(\"events\", [])     or []\n",
        "    markets    = data.get(\"markets\", [])    or []\n",
        "    selections = data.get(\"selections\", []) or []\n",
        "\n",
        "    event_map = {}\n",
        "    for ev in events:\n",
        "        name = ev.get(\"name\") or f\"{ev.get('awayTeamName','')} @ {ev.get('homeTeamName','')}\"\n",
        "        event_map[ev.get(\"id\")] = name\n",
        "\n",
        "    market_map = {m.get(\"id\"): m for m in markets}\n",
        "\n",
        "    odds_dict = {}\n",
        "    seen = set()\n",
        "\n",
        "    for sel in selections:\n",
        "        if str(sel.get(\"label\", \"\")).strip() != \"1+\":\n",
        "            continue\n",
        "        player_name = \"Unknown\"\n",
        "        participants = sel.get(\"participants\") or []\n",
        "        if participants:\n",
        "            names = [\n",
        "                (p.get(\"name\") or p.get(\"displayName\") or f\"P{p.get('id','')}\")\n",
        "                for p in participants\n",
        "                if p.get(\"type\") in (None, \"Player\")\n",
        "            ]\n",
        "            if names:\n",
        "                player_name = \", \".join(names)\n",
        "        if player_name in seen:\n",
        "            continue\n",
        "        seen.add(player_name)\n",
        "        odds = None\n",
        "        display_odds = sel.get(\"displayOdds\") or {}\n",
        "        if isinstance(display_odds, dict) and display_odds.get(\"american\") is not None:\n",
        "            odds = display_odds[\"american\"]\n",
        "        elif sel.get(\"americanOdds\") is not None:\n",
        "            odds = str(sel[\"americanOdds\"])\n",
        "        if odds is None:\n",
        "            continue\n",
        "        if isinstance(odds, str):\n",
        "            odds = int(odds.replace('+', ''))\n",
        "        decimal = (odds / 100) + 1 if odds > 0 else (100 / abs(odds)) + 1\n",
        "        clean = re.sub(r'[^\\w\\s]', '', player_name).lower()\n",
        "        odds_dict[clean] = {\"american\": odds, \"decimal\": decimal, \"original\": player_name}\n",
        "    print(f\"✅ Fetched odds for {len(odds_dict)} players\")\n",
        "    return odds_dict\n",
        "\n",
        "def add_odds_and_ev(df_pred):\n",
        "    odds = fetch_draftkings_odds()\n",
        "    if not odds:\n",
        "        print(\"No odds fetched. Skipping EV calculation.\")\n",
        "        df_pred['ev'] = -1\n",
        "        return df_pred\n",
        "\n",
        "    def norm_name(name):\n",
        "        if ',' in name:\n",
        "            parts = name.split(',')\n",
        "            name = (parts[1].strip() + ' ' + parts[0].strip()).lower()\n",
        "        else:\n",
        "            name = name.lower()\n",
        "        name = re.sub(r'\\s*(jr\\.|sr\\.|ii|iii|iv)$', '', name)\n",
        "        name = re.sub(r'[^\\w\\s]', '', name)\n",
        "        return name.strip()\n",
        "\n",
        "    df_pred['norm_name'] = df_pred['batter_name'].apply(norm_name)\n",
        "    df_pred['decimal_odds'] = 0.0\n",
        "    df_pred['american_odds'] = 0\n",
        "    df_pred['ev'] = -1.0\n",
        "\n",
        "    odds_keys = list(odds.keys())\n",
        "    from difflib import get_close_matches\n",
        "    for idx, row in df_pred.iterrows():\n",
        "        key = row['norm_name']\n",
        "        if key in odds:\n",
        "            df_pred.at[idx, 'decimal_odds'] = odds[key]['decimal']\n",
        "            df_pred.at[idx, 'american_odds'] = odds[key]['american']\n",
        "            df_pred.at[idx, 'ev'] = row['hr_probability'] * odds[key]['decimal'] - 1\n",
        "        else:\n",
        "            match = get_close_matches(key, odds_keys, n=1, cutoff=0.8)\n",
        "            if match:\n",
        "                best = match[0]\n",
        "                df_pred.at[idx, 'decimal_odds'] = odds[best]['decimal']\n",
        "                df_pred.at[idx, 'american_odds'] = odds[best]['american']\n",
        "                df_pred.at[idx, 'ev'] = row['hr_probability'] * odds[best]['decimal'] - 1\n",
        "    return df_pred\n",
        "\n",
        "# ----------------------------------------------------------------------------\n",
        "# DARK THEMED HTML DASHBOARD\n",
        "# ----------------------------------------------------------------------------\n",
        "def generate_dashboard(df_pred, today):\n",
        "    top10_likely = df_pred.nlargest(10, 'hr_probability')[\n",
        "        ['batter_name', 'pitcher_name', 'home_team', 'hr_probability']\n",
        "    ].copy()\n",
        "    top10_likely['hr_probability'] = top10_likely['hr_probability'].apply(lambda x: f\"{x:.3f} ({x*100:.1f}%)\")\n",
        "\n",
        "    positive_ev = df_pred[df_pred['ev'] > 0].sort_values('ev', ascending=False)\n",
        "    top10_ev = positive_ev.head(10)[\n",
        "        ['batter_name', 'pitcher_name', 'home_team', 'hr_probability', 'american_odds', 'ev']\n",
        "    ].copy()\n",
        "    top10_ev['hr_probability'] = top10_ev['hr_probability'].apply(lambda x: f\"{x:.3f} ({x*100:.1f}%)\")\n",
        "    top10_ev['american_odds'] = top10_ev['american_odds'].apply(lambda x: f\"+{x}\" if x > 0 else str(x))\n",
        "    top10_ev['ev'] = top10_ev['ev'].apply(lambda x: f\"{x:.3f}\")\n",
        "\n",
        "    def _generate_table_rows(df, mode):\n",
        "        rows = \"\"\n",
        "        for _, row in df.iterrows():\n",
        "            if mode == 'prob':\n",
        "                rows += f\"\"\"\n",
        "                <tr>\n",
        "                    <td>{row['batter_name']}</td>\n",
        "                    <td>{row['pitcher_name']}</td>\n",
        "                    <td>{row['home_team']}</td>\n",
        "                    <td class=\"prob\">{row['hr_probability']}</td>\n",
        "                </tr>\"\"\"\n",
        "            else:\n",
        "                rows += f\"\"\"\n",
        "                <tr>\n",
        "                    <td>{row['batter_name']}</td>\n",
        "                    <td>{row['pitcher_name']}</td>\n",
        "                    <td>{row['home_team']}</td>\n",
        "                    <td class=\"prob\">{row['hr_probability']}</td>\n",
        "                    <td class=\"odds\">{row['american_odds']}</td>\n",
        "                    <td class=\"ev\">{row['ev']}</td>\n",
        "                </tr>\"\"\"\n",
        "        return rows\n",
        "\n",
        "    html = f\"\"\"\n",
        "<!DOCTYPE html>\n",
        "<html>\n",
        "<head>\n",
        "    <meta charset=\"UTF-8\">\n",
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=yes\">\n",
        "    <title>MLB Home Run Dashboard – {today}</title>\n",
        "    <style>\n",
        "        * {{ margin: 0; padding: 0; box-sizing: border-box; }}\n",
        "        body {{ background: #0a0c10; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, sans-serif; padding: 20px; color: #e0e0e0; }}\n",
        "        .container {{ max-width: 800px; margin: 0 auto; }}\n",
        "        .header {{ text-align: center; margin-bottom: 30px; }}\n",
        "        .header h1 {{ font-size: 1.8rem; font-weight: 600; background: linear-gradient(135deg, #ffb347, #ff6b6b); -webkit-background-clip: text; background-clip: text; color: transparent; margin-bottom: 8px; }}\n",
        "        .header p {{ color: #8e8e93; font-size: 0.9rem; }}\n",
        "        .card {{ background: #1c1e24; border-radius: 20px; padding: 20px; margin-bottom: 30px; box-shadow: 0 4px 12px rgba(0,0,0,0.3); }}\n",
        "        .card-title {{ font-size: 1.4rem; font-weight: 600; margin-bottom: 16px; border-left: 4px solid #ff6b6b; padding-left: 12px; }}\n",
        "        table {{ width: 100%; border-collapse: collapse; }}\n",
        "        th {{ text-align: left; padding: 12px 8px; background: #2c2e36; color: #ffb347; font-weight: 600; font-size: 0.85rem; border-radius: 12px 12px 0 0; }}\n",
        "        td {{ padding: 10px 8px; border-bottom: 1px solid #2c2e36; font-size: 0.9rem; }}\n",
        "        tr:last-child td {{ border-bottom: none; }}\n",
        "        .prob {{ font-weight: 600; color: #4cd964; }}\n",
        "        .odds {{ font-weight: 600; color: #ff9f0a; }}\n",
        "        .ev {{ font-weight: 600; color: #ff3b30; }}\n",
        "        .footnote {{ text-align: center; font-size: 0.75rem; color: #636366; margin-top: 20px; }}\n",
        "        @media (max-width: 600px) {{\n",
        "            body {{ padding: 12px; }}\n",
        "            .card {{ padding: 12px; }}\n",
        "            th, td {{ font-size: 0.75rem; padding: 8px 4px; }}\n",
        "            .card-title {{ font-size: 1.2rem; }}\n",
        "        }}\n",
        "    </style>\n",
        "</head>\n",
        "<body>\n",
        "<div class=\"container\">\n",
        "    <div class=\"header\">\n",
        "        <h1>⚾ Home Run Predictor</h1>\n",
        "        <p>{today}</p>\n",
        "    </div>\n",
        "    <div class=\"card\">\n",
        "        <div class=\"card-title\">🔮 Top 10 Most Likely Home Runs</div>\n",
        "        <table>\n",
        "            <thead><tr><th>Batter</th><th>Pitcher</th><th>Home Team</th><th>Probability</th></tr></thead>\n",
        "            <tbody>{_generate_table_rows(top10_likely, 'prob')}</tbody>\n",
        "        </table>\n",
        "    </div>\n",
        "    <div class=\"card\">\n",
        "        <div class=\"card-title\">💰 Top 10 +EV Bets (EV > 0)</div>\n",
        "        <table>\n",
        "            <thead><tr><th>Batter</th><th>Pitcher</th><th>Team</th><th>Model Prob</th><th>DK Odds</th><th>EV</th></tr></thead>\n",
        "            <tbody>{_generate_table_rows(top10_ev, 'ev')}</tbody>\n",
        "        </table>\n",
        "    </div>\n",
        "    <div class=\"footnote\">\n",
        "        Expected Value (EV) = (Model Probability × Decimal Odds) − 1 | Positive EV indicates a mathematically profitable bet.\n",
        "    </div>\n",
        "</div>\n",
        "</body>\n",
        "</html>\n",
        "\"\"\"\n",
        "    return html\n",
        "\n",
        "# ----------------------------------------------------------------------------\n",
        "# GITHUB PUSH FUNCTION\n",
        "# ----------------------------------------------------------------------------\n",
        "def push_to_github(dashboard_html, filename=\"index.html\"):\n",
        "    import os\n",
        "    from subprocess import run\n",
        "\n",
        "    token = os.environ.get('GITHUB_TOKEN')\n",
        "    if not token:\n",
        "        print(\"⚠️ GITHUB_TOKEN not found. Skipping GitHub push.\")\n",
        "        return False\n",
        "\n",
        "    repo_url = f\"https://{GITHUB_USERNAME}:{token}@github.com/{GITHUB_USERNAME}/{GITHUB_REPO}.git\"\n",
        "    try:\n",
        "        if not os.path.exists(GITHUB_REPO):\n",
        "            run([\"git\", \"clone\", repo_url], check=True)\n",
        "        os.chdir(GITHUB_REPO)\n",
        "        run([\"git\", \"pull\"], check=True)\n",
        "    except Exception as e:\n",
        "        print(f\"⚠️ Git setup error: {e}\")\n",
        "        os.chdir(\"..\")\n",
        "        return False\n",
        "\n",
        "    with open(filename, \"w\") as f:\n",
        "        f.write(dashboard_html)\n",
        "\n",
        "    try:\n",
        "        run([\"git\", \"config\", \"user.email\", f\"{GITHUB_USERNAME}@users.noreply.github.com\"], check=True)\n",
        "        run([\"git\", \"config\", \"user.name\", GITHUB_USERNAME], check=True)\n",
        "        run([\"git\", \"add\", filename], check=True)\n",
        "        run([\"git\", \"commit\", \"-m\", f\"Daily dashboard update {TODAY}\"], check=True)\n",
        "        run([\"git\", \"push\"], check=True)\n",
        "        print(f\"✅ Dashboard pushed to GitHub: {filename}\")\n",
        "        os.chdir(\"..\")\n",
        "        return True\n",
        "    except Exception as e:\n",
        "        print(f\"❌ Git push error: {e}\")\n",
        "        os.chdir(\"..\")\n",
        "        return False\n",
        "\n",
        "# ----------------------------------------------------------------------------\n",
        "# MAIN\n",
        "# ----------------------------------------------------------------------------\n",
        "def main():\n",
        "    drive.mount('/content/drive')\n",
        "    output_folder = \"/content/drive/MyDrive/mlb_hr_data/\"\n",
        "    !mkdir -p \"$output_folder\"\n",
        "\n",
        "    plate_dict = fetch_plate_discipline()\n",
        "    static_data = load_static_csvs()\n",
        "\n",
        "    df_pred = fetch_todays_features(plate_dict, static_data)\n",
        "    df_train = load_training_data()\n",
        "    df_pred = train_and_predict(df_train, df_pred)\n",
        "    df_pred = add_odds_and_ev(df_pred)\n",
        "\n",
        "    # Console output\n",
        "    print(\"\\n\" + \"=\"*80)\n",
        "    print(f\"🔮 TOP 10 MOST LIKELY HOME RUNS FOR {TODAY}\")\n",
        "    print(\"=\"*80)\n",
        "    top10 = df_pred.nlargest(10, 'hr_probability')[['batter_name', 'pitcher_name', 'home_team', 'hr_probability']]\n",
        "    for _, row in top10.iterrows():\n",
        "        print(f\"{row['batter_name']:25} vs {row['pitcher_name']:25} ({row['home_team']}) → {row['hr_probability']:.3f} ({row['hr_probability']*100:.1f}%)\")\n",
        "\n",
        "    print(\"\\n\" + \"=\"*80)\n",
        "    print(f\"💰 TOP 10 HIGHEST EXPECTED VALUE BETS FOR {TODAY} (EV > 0)\")\n",
        "    print(\"=\"*80)\n",
        "    positive_ev = df_pred[df_pred['ev'] > 0].sort_values('ev', ascending=False)\n",
        "    if len(positive_ev) == 0:\n",
        "        print(\"No +EV bets found today.\")\n",
        "    else:\n",
        "        for _, row in positive_ev.head(10).iterrows():\n",
        "            print(f\"{row['batter_name']:25} vs {row['pitcher_name']:25} ({row['home_team']})\")\n",
        "            print(f\"   Model Prob: {row['hr_probability']:.3f} ({row['hr_probability']*100:.1f}%) | DK Odds: {row['american_odds']:+d} | EV: {row['ev']:.3f}\\n\")\n",
        "\n",
        "    # Generate and display dashboard\n",
        "    dashboard_html = generate_dashboard(df_pred, TODAY)\n",
        "    from IPython.display import display, HTML\n",
        "    display(HTML(dashboard_html))\n",
        "\n",
        "    # Save local copy\n",
        "    output_html_path = f\"{output_folder}hr_dashboard_{TODAY}.html\"\n",
        "    with open(output_html_path, \"w\") as f:\n",
        "        f.write(dashboard_html)\n",
        "    print(f\"✅ Dashboard saved locally to {output_html_path}\")\n",
        "\n",
        "    # Push to GitHub\n",
        "    push_to_github(dashboard_html, filename=\"index.html\")\n",
        "    push_to_github(dashboard_html, filename=f\"hr_dashboard_{TODAY}.html\")\n",
        "\n",
        "    # Save CSV\n",
        "    output_path = f\"{output_folder}hr_predictions_with_odds_{TODAY}.csv\"\n",
        "    df_pred.to_csv(output_path, index=False)\n",
        "    print(f\"✅ Full results saved to {output_path}\")\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()"
      ],
      "metadata": {
        "id": "mCGxPJ6lfJnA"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}